#!/usr/bin/perl
# D3: plugin's _is_retryable_error matches /rate limit/i, so a write that
# receives 'Rate Limit Exceeded' is retried up to api_retry_max times.
# Each retry calls _ws_open_ephemeral -> auth.login_* -> another counted
# login inside the same 60s window where the limiter cannot recover.
# Result: ~4 logins per single failed write, lockout extended.
#
# Expected after fix:
#   - 'Rate Limit Exceeded' NOT in the retryable-error set
#   - integration: after limiter is tripped, one write does not generate
#     additional logins via retry storm
#
# fix/rate-limit-connection-reuse: _is_connection_error no longer matches
# /rate limit/, so _is_retryable_error returns 0 for an EBUSY string.
# There is no dedicated _is_rate_limit_error classifier on this branch.
# Pre-trip uses _ws_open (no _ws_open_ephemeral here); each call opens a
# fresh authenticated WS so 25 of them still trip the 20/60s limiter.
#
# This test is destructive: it pre-trips the per-IP limiter, then runs one
# write. Schedule as the last test before any drain-dependent ones.

use strict;
use warnings;
use FindBin qw($Bin);
use lib "$Bin/lib";
use Test::More;
use Time::HiRes qw(sleep);
use RateLimit::Harness qw(env_require env_get drain_limiter new_audit_conn count_logins
                          now_iso qm_create_with_disk qm_destroy test_scfg say_diag);

plan tests => 4;

# Unit assertion first — independent of TN state.
require PVE::Storage::Custom::TrueNASPlugin;
my $rl_err = "JSON-RPC error: ... CallError('Rate Limit Exceeded', 16) ... errname=EBUSY";
ok(!PVE::Storage::Custom::TrueNASPlugin::_is_retryable_error($rl_err),
    "Rate Limit Exceeded must NOT be retryable (D3 fix)");

new_audit_conn();
drain_limiter();

my $sid  = env_require('STORAGE_ID');
my $vmid = env_get('TEST_VMID_BASE', 99000) + 30;
my $scfg = test_scfg();

# Pre-trip: drive 25 fresh logins quickly to push past the 20/60s threshold.
# _ws_open authenticates on every call, so each is one login.
say_diag("pre-tripping limiter: 25 fresh _ws_open logins");
my $tripped = 0;
for (1 .. 25) {
    eval {
        my $c = PVE::Storage::Custom::TrueNASPlugin::_ws_open($scfg);
        eval { $c->{sock}->close() if $c && $c->{sock} };
    };
    $tripped++ if $@ && $@ =~ /Rate Limit Exceeded|EBUSY/i;
}
ok($tripped > 0, "limiter tripped during pre-trip (saw $tripped EBUSY)")
    or diag("If zero, the 20/60s threshold may differ from documented; check TN version");

# Window starts AFTER pre-trip — we only count logins generated by the
# single write attempt below.
sleep 1;
my $t_start = now_iso();
my ($rc, $out) = qm_create_with_disk($vmid, $sid, 1);
sleep 2;
my $t_end = now_iso();
my $logins = count_logins($t_start, $t_end);
say_diag("logins during one create against a tripped limiter: $logins; rc=$rc");

# Post-fix expectation: write either rides existing persistent socket (0
# logins, succeeds) OR fails fast with the rate-limit error (0 logins).
# Either way, NOT a retry storm that generates additional logins.
cmp_ok($logins, '<=', 1,
    "tripped-limiter write generates at most 1 auth.login_* (D3 fix prevents amplification)");

# Cleanup
if ($rc == 0) {
    my ($crc, $cout) = qm_destroy($vmid);
    is($crc, 0, "cleanup: destroy succeeded VM") or diag("cleanup output: $cout");
} else {
    pass("create failed under tripped limiter; nothing to cleanup");
}

# Drain so the limiter resets cleanly for any later run.
sleep 90;

done_testing();
